version: '3'

name: tcd

services:

  db:
    image: postgres:16-alpine3.18
    volumes:
      - vol_db:/var/lib/postgresql/data
      # - ./images/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: tcd
      POSTGRES_USER: tcd
      POSTGRES_PASSWORD: ft_password

  dbadmin:
    build: ./images/adminer
    image: tcd/adminer
    ports: [127.0.0.1:8080:80]
    environment: [QS=pgsql=db]

  backend:
    build: ./images/django
    image: tcd/django
    restart: unless-stopped
    depends_on: [db]
    ports: [8800:8000]
    volumes:
      - vol_app:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: tcd
      POSTGRES_USER: tcd
      POSTGRES_PASSWORD: ft_password
      CLIENT_ID: u-s4t2ud-888abf99e7a96317ce8952769a0be4b4c4a092bed5f52d27b85ae3b989536a15
      CLIENT_SECRET: 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
      HTTP_HOSTNAME: baa3-27-125-246-141.ngrok-free.app
    # command: sleep infinity

  frontend:
    build: ./images/nginx
    image: tcd/nginx
    depends_on: [backend]
    ports: ["443:443"]
    # environment:
    #   SSL_DOMAIN: $DOMAIN

volumes:

  vol_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./images/django/app

  vol_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/db
