version: '3'

name: tcd

include:
  - development.yml

services:

  db:
    image: postgres:16-alpine3.19
    volumes:
      - vol_db:/var/lib/postgresql/data
      # - ./images/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: tcd
      POSTGRES_USER: tcd
      POSTGRES_PASSWORD: ft_password

  backend:
    build: ./images/django
    image: tcd/django
    restart: unless-stopped
    depends_on: [db]
    # internal testing port. public access via nginx
    ports: [127.0.0.1:8000:80]
    volumes:
      - vol_app:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: tcd
      POSTGRES_USER: tcd
      POSTGRES_PASSWORD: ft_password
      CLIENT_ID: u-s4t2ud-888abf99e7a96317ce8952769a0be4b4c4a092bed5f52d27b85ae3b989536a15
      CLIENT_SECRET: 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
      HTTP_HOSTNAME: unduly-right-sloth.ngrok-free.app
    # command: sleep infinity

  frontend:
    depends_on: [backend]
    build: ./images/nginx
    image: tcd/nginx
    ports: [443:443, 80:80]
    volumes:
      - ./images/django/app/static:/static:ro
    # environment:
    #   SSL_DOMAIN: $DOMAIN

volumes:

  vol_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./images/django/app

  vol_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/db
